import test from 'node:test';
import assert from 'node:assert/strict';
import {fromSnapshot,schedulePayload,canManage} from '../lib/supabase/snapshot.ts';
import {addDays,blocks,totals,generate} from '../lib/rota/engine.ts';
const member=(id,role='engineer',status='approved')=>({id,email:id+'@example.invalid',name:id,role,status,active:true,seniority:1,color:'#adc9ee'});
const row=(day,primary='admin',publication=null,options={})=>({id:(publication??'draft')+'-'+day,publication_id:publication,day,end_day:addDays(day,1),primary_id:primary,secondary_id:null,manager_override:false,title:'',extra_points:0,points:1,...options});
function fixture(){return {revision:4,members:[member('admin','admin'),member('engineer'),member('waiting','engineer','pending')],roles:[{code:'admin',label:'Admin',can_manage:true},{code:'engineer',label:'Engineer',can_manage:false}],memberStatuses:[],monthStatuses:[],constraintTypes:[],months:[{month:'2026-10',deadline:'2026-09-24',status:'draft',generated:true,current_publication_id:'v2',publication_sequence:2}],constraints:[{member_id:'engineer',day:'2026-10-01',kind:'no',note:'Vacation'}],assignments:[row('2026-10-01','admin'),row('2026-10-01','admin','v1'),row('2026-10-01','engineer','v2')],publications:[{id:'v1',month:'2026-10',version:1,published_at:'2026-09-20',published_by:'admin'},{id:'v2',month:'2026-10',version:2,published_at:'2026-09-21',published_by:'admin'}]}}
test('admin sees only draft rows and approved engineers',()=>{const state=fromSnapshot(fixture(),'admin');assert.equal(state.assignments['2026-10-01'].primary,'admin');assert.equal(state.months['2026-10'].status,'draft');assert.deepEqual(state.team.map(m=>m.id),['admin','engineer']);assert.equal(state.constraintNotes.engineer['2026-10-01'],'Vacation')});
test('engineer sees current publication while admins edit a draft',()=>{const state=fromSnapshot(fixture(),'engineer');assert.equal(state.assignments['2026-10-01'].primary,'engineer');assert.equal(state.months['2026-10'].status,'published')});
test('unpublished and historical rows never enter the current engineer view',()=>{const raw=fixture();raw.months[0].current_publication_id=null;assert.deepEqual(fromSnapshot(raw,'engineer').assignments,{})});
test('version preview reads precisely the selected version',()=>{const state=fromSnapshot(fixture(),'admin','v1');assert.equal(state.assignments['2026-10-01'].primary,'admin');assert.equal(Object.keys(state.assignments).length,1)});
test('schedule saves omit notes, profile names and membership roles',()=>{const state=fromSnapshot(fixture(),'admin'),payload=schedulePayload(state);assert.equal(payload.constraints,undefined);assert.equal(payload.constraintNotes,undefined);assert.equal(payload.team[0].role,undefined);assert.equal(payload.team[0].name,undefined);assert.equal(payload.team[0].email,undefined)});
test('role capabilities come from the role lookup',()=>{const raw=fixture();raw.members[1].role='admin';assert.equal(canManage(raw,'engineer'),true);raw.roles[0].can_manage=false;assert.equal(canManage(raw,'admin'),false)});
test('combined weekend is a single stored duty row',()=>{const raw=fixture();raw.assignments=[row('2026-10-02','admin',null,{end_day:'2026-10-04'})];const state=fromSnapshot(raw,'admin');assert.equal(blocks('2026-10',state.specials,state.splitWeekends).find(b=>b.start==='2026-10-02').points,1);const payload=schedulePayload(state);assert.equal(payload.duties.find(r=>r.day==='2026-10-02').end_day,'2026-10-04');assert.equal(payload.duties.some(r=>r.day==='2026-10-03'),false)});
test('holiday points survive reassignment and split-weekend round trip',()=>{const raw=fixture();raw.assignments=[row('2026-10-02','admin',null,{title:'Holiday',extra_points:2,points:2.5}),row('2026-10-03','engineer',null,{points:0.5})];const state=fromSnapshot(raw,'admin');state.assignments['2026-10-02'].primary='engineer';const payload=schedulePayload(state);assert.equal(payload.duties.find(r=>r.day==='2026-10-02').extra_points,2);assert.equal(payload.duties.find(r=>r.day==='2026-10-02').primary_id,'engineer');assert.equal(payload.duties.find(r=>r.day==='2026-10-03').extra_points,0);assert.equal(totals(state,blocks('2026-10',state.specials,state.splitWeekends)).engineer,3)});
test('new workspace stays empty until generation is requested',()=>{const raw=fixture();raw.assignments=[];raw.publications=[];raw.months=[];const state=fromSnapshot(raw,'admin');assert.deepEqual(state.assignments,{});assert.deepEqual(schedulePayload(state).duties,[])});
test('Friday owner publication wins across a month boundary',()=>{const raw=fixture();raw.months=[{month:'2026-07',deadline:'2026-06-24',status:'published',current_publication_id:'july'},{month:'2026-08',deadline:'2026-07-24',status:'published',current_publication_id:'august'}];raw.publications=[{id:'july',month:'2026-07'},{id:'august',month:'2026-08'}];raw.assignments=[row('2026-07-31','admin','august',{end_day:'2026-08-02'}),row('2026-07-31','engineer','july'),row('2026-08-01','admin','july')];const state=fromSnapshot(raw,'engineer');assert.equal(state.assignments['2026-07-31'].primary,'engineer');assert.equal(state.assignments['2026-08-01'].primary,'admin');assert.deepEqual(state.splitWeekends,['2026-07-31'])});
