import test from 'node:test';
import assert from 'node:assert/strict';
import {fromSnapshot,schedulePayload} from '../lib/supabase/snapshot.ts';
const member=(id,role='engineer',status='approved')=>({id,email:id+'@example.invalid',name:id,role,status,active:true,seniority:1,color:'#adc9ee'});
function fixture(){return {revision:4,members:[member('manager','manager'),member('engineer'),member('waiting','engineer','pending')],months:[{month:'2026-10',deadline:'2026-09-24',status:'draft',generated:true}],constraints:[{member_id:'engineer',day:'2026-10-01',kind:'no',note:'Vacation'}],specials:[],splits:[],assignments:[{day:'2026-10-01',primary_id:'manager',secondary_id:null,manager_override:false}],publications:[{month:'2026-10',published_at:'2026-09-20',payload:{assignments:{'2026-10-01':{primary:'engineer'}},specials:[],splitWeekends:[]}}]}}
test('manager sees editable draft and approved engineers only',()=>{const state=fromSnapshot(fixture(),'manager');assert.equal(state.assignments['2026-10-01'].primary,'manager');assert.equal(state.months['2026-10'].status,'draft');assert.deepEqual(state.team.map(m=>m.id),['manager','engineer']);assert.equal(state.constraintNotes.engineer['2026-10-01'],'Vacation')});
test('engineer sees last publication while manager edits a newer draft',()=>{const state=fromSnapshot(fixture(),'engineer');assert.equal(state.assignments['2026-10-01'].primary,'engineer');assert.equal(state.months['2026-10'].status,'published')});
test('unpublished assignments are never used in engineer view',()=>{const raw=fixture();raw.publications=[];const state=fromSnapshot(raw,'engineer');assert.deepEqual(state.assignments,{});assert.equal(state.months['2026-10'].status,'draft')});
test('schedule saves omit constraints, notes and membership roles',()=>{const raw=fixture(),state=fromSnapshot(raw,'manager'),payload=schedulePayload(state);assert.equal(payload.constraints,undefined);assert.equal(payload.constraintNotes,undefined);assert.equal(payload.team[0].role,undefined);assert.equal(payload.team[0].email,undefined);assert.equal(payload.assignments,state.assignments)});
