'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Check,Plus,Sparkles,Users,SlidersHorizontal,ArrowUp,ArrowDown,Lock,Info,Download,CheckCircle2,Globe,ArrowRight,ShieldCheck,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AvailabilityEditor} from '@/components/rota/availability-editor';
import {useHoldDrag} from '@/hooks/use-hold-drag';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {addDays,dayOf,monthNext,dates,blocks,unavailable,overlap,totals,allKnownBlocks,generate,demo,applyConstraints,swapDraft,type State,type Duty,type Assignment} from '@/lib/rota/engine';
const KEY='duty-demo-v1';
function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [state,setState]=useState<State>(()=>{const s=demo();s.assignments=generate(s,'2026-10').assignments;s.months['2026-10'].generated=true;return s}),[ready,setReady]=useState(false),[month,setMonth]=useState('2026-10'),[lang,setLang]=useState<'en'|'he'>('en'),[tab,setTab]=useState('schedule');
 const [selected,setSelected]=useState<Duty|null>(null),[specialOpen,setSpecialOpen]=useState(false),[help,setHelp]=useState(false),[settings,setSettings]=useState(false),[publishOpen,setPublishOpen]=useState(false);
 const [person,setPerson]=useState('e0'),[view,setView]=useState('team'),[primary,setPrimary]=useState('none'),[secondary,setSecondary]=useState('none'),[locked,setLocked]=useState(false),[override,setOverride]=useState(false);
 const [specialTitle,setSpecialTitle]=useState(''),[specialStart,setSpecialStart]=useState('2026-10-01'),[specialEnd,setSpecialEnd]=useState('2026-10-02'),[extra,setExtra]=useState('1'),[newName,setNewName]=useState(''),[busy,setBusy]=useState(false);
 const [swap,setSwap]=useState<{from:string;to:string}|null>(null),[swapOverride,setSwapOverride]=useState(false),[swapTarget,setSwapTarget]=useState('none'),[dragFrom,setDragFrom]=useState<string|null>(null),[dragOver,setDragOver]=useState<string|null>(null);
 const dragSource=useRef<string|null>(null);
const t=(en:string,he:string)=>lang==='en'?en:he;
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved);if(parsed.version===1&&Array.isArray(parsed.team)&&parsed.months&&parsed.constraints&&parsed.assignments&&parsed.specials)setState(parsed);}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast.error(t('Could not save on this device. Export a backup.','לא ניתן לשמור במכשיר. יש לייצא גיבוי.'))}},[state,ready]);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr'},[lang]);
 const bs=useMemo(()=>blocks(month,state.specials),[month,state.specials]);
 const md=state.months[month]??{deadline:addDays(month+'-01',-7),status:'draft' as const};
 const owned=bs.filter(b=>b.start.slice(0,7)===month),active=state.team.filter(p=>p.active),monthTotals=totals(state,owned),historyTotals=totals(state,allKnownBlocks(state).filter(b=>b.start<monthNext(month)+'-01'));
 const assigned=bs.filter(b=>state.assignments[b.id]?.primary).length;
 const conflicts=bs.filter(b=>{const a=state.assignments[b.id];return a&&[a.primary,a.secondary].some(id=>id&&unavailable(b,id,state.constraints).length)&&!a.override});
 const gaps=active.flatMap(p=>{const mine=allKnownBlocks(state).filter(b=>state.assignments[b.id]?.primary===p.id||state.assignments[b.id]?.secondary===p.id);return mine.filter((b,i)=>i>0&&b.start===mine[i-1].end&&(b.start.slice(0,7)===month||mine[i-1].start.slice(0,7)===month)).map(b=>({p,b}));});
 const locale=lang==='en'?'en-GB':'he-IL';
 const fmt=(d:string,opts:Intl.DateTimeFormatOptions={day:'numeric',month:'short'})=>new Date(d+'T12:00:00Z').toLocaleDateString(locale,{...opts,timeZone:'Asia/Jerusalem'});
 const monthLabel=fmt(month+'-15',{month:'long',year:'numeric'});
 const personName=(id?:string)=>state.team.find(p=>p.id===id)?.name??t('Unassigned','ללא שיבוץ');
 const nickname=(id?:string)=>personName(id).split(' ')[0];
 const dateCells=dates(addDays(month+'-01',-dayOf(month+'-01')),addDays(monthNext(month)+'-01',(7-dayOf(monthNext(month)+'-01'))%7));
 function update(fn:(s:State)=>State,draft=true){setState(s=>{const n=fn(s);if(!draft)return n;const months={...n.months,[month]:{...(n.months[month]??md),status:'draft' as const}};for(const b of [...allKnownBlocks(s),...allKnownBlocks(n)]){const changed=JSON.stringify(s.assignments[b.id])!==JSON.stringify(n.assignments[b.id])||JSON.stringify(s.specials)!==JSON.stringify(n.specials);if(changed)for(const m of Object.keys(months))if(overlap(b,{start:m+'-01',end:monthNext(m)+'-01'}))months[m]={...months[m],status:'draft'};}return {...n,months}})}
 function changeMonth(n:number){const m=monthNext(month,n);setMonth(m);setSpecialStart(m+'-01');setSpecialEnd(m+'-02');}
 function runGenerate(){setBusy(true);setTimeout(()=>{const r=generate(state,month,crypto.getRandomValues(new Uint32Array(1))[0]);update(s=>({...s,assignments:r.assignments,months:{...s.months,[month]:{...md,generated:true,status:'draft'}}}));setBusy(false);toast.success(r.warnings.length?t(`${r.warnings.length} duties need your decision.`,'יש תורנויות שממתינות להחלטה שלך.'):t('Draft ready. Review, adjust, then publish.','הטיוטה מוכנה לבדיקה, עריכה ופרסום.'))},40)}
 function openDuty(b:Duty){const a=state.assignments[b.id];setSelected(b);setPrimary(a?.primary||'none');setSecondary(a?.secondary||'none');setLocked(!!a?.locked);setOverride(false)}
 const carry=selected&&selected.start.slice(0,7)!==month;
 const editConflicts=selected?[primary,secondary].filter(p=>p!=='none').flatMap(id=>unavailable(selected,id,state.constraints).map(d=>`${personName(id)} · ${fmt(d)}${state.constraintNotes?.[id]?.[d]?' · '+state.constraintNotes[id][d]:''}`)):[];
 function saveDuty(){if(!selected||carry)return;if(primary!=='none'&&primary===secondary){toast.error(t('Choose two different engineers.','יש לבחור שני מהנדסים שונים.'));return}if(editConflicts.length&&!override)return;
 const a:Assignment={primary:primary==='none'?'':primary,secondary:secondary==='none'?undefined:secondary,locked,override:editConflicts.length?override:undefined};
 update(s=>({...s,assignments:{...s.assignments,[selected.id]:a}}));setSelected(null);toast.success(t('Assignment saved to draft.','השיבוץ נשמר בטיוטה.'))}
 function addSpecial(){if(!/^\d{4}-\d{2}-\d{2}$/.test(specialStart)||!/^\d{4}-\d{2}-\d{2}$/.test(specialEnd)||specialEnd<specialStart||(Date.parse(specialEnd)-Date.parse(specialStart))/86400000>=14){toast.error(t('Choose a valid block of 1–14 days.','יש לבחור מקטע תקין של 1–14 ימים.'));return}const end=addDays(specialEnd,1),x={id:crypto.randomUUID(),title:specialTitle.trim()||t('Special duty','תורנות מיוחדת'),start:specialStart,end,extra:Number(extra)};
 if(!/^\d{4}-\d{2}-\d{2}$/.test(x.start)||specialEnd<x.start||x.start.slice(0,7)!==month||dates(x.start,end).length>14||!Number.isFinite(x.extra)||x.extra<0||x.extra>20){toast.error(t('Choose up to 14 days starting this month, and 0–20 extra points.','יש לבחור עד 14 ימים שמתחילים בחודש זה ו־0–20 נקודות נוספות.'));return}
 if(state.specials.some(s=>overlap(s,x))){toast.error(t('This overlaps another special block. Remove it first.','קיימת חפיפה עם מקטע מיוחד אחר.'));return}
 const touched=allKnownBlocks(state).filter(b=>overlap(b,x));if(touched.some(b=>b.start.slice(0,7)!==month&&state.assignments[b.id]?.primary)){toast.error(t('This overlaps an assigned duty from another month. Edit that month first.','יש חפיפה לשיבוץ מחודש אחר. יש לערוך אותו קודם.'));return}
 update(s=>{const assignments={...s.assignments};touched.forEach(b=>delete assignments[b.id]);const months={...s.months};for(const m of Object.keys(months))if(m+'-01'<end&&monthNext(m)+'-01'>x.start)months[m]={...months[m],status:'draft'};return {...s,assignments,months,specials:[...s.specials,x]}});setSpecialOpen(false);toast.success(t('Special block added. Generate to fill its assignment.','המקטע נוסף. ניתן ליצור שיבוץ חדש.'))}
 function saveConstraints(days:string[],kind:'no'|'prefer'|'clear',note:string){try{const next=applyConstraints(state,person,days,kind,note);update(()=>next);toast.success(t('Constraints saved.','האילוצים נשמרו.'))}catch{toast.error(t('Reopen the draft to edit constraints.','יש לפתוח טיוטה לעריכת אילוצים.'))}}
 function startSwap(from:string,to:string){if(from===to)return;setSwapOverride(false);setSwap({from,to});}
 const drag=useHoldDrag({enabled:md.status==='draft'&&tab==='schedule',onStart:key=>{if(state.assignments[key]?.locked||key.slice(0,7)!==month||!state.assignments[key]?.primary){dragSource.current=null;return}dragSource.current=key;setDragFrom(key);},onMove:key=>{if(dragSource.current)setDragOver(key)},onEnd:key=>{const source=dragSource.current;dragSource.current=null;setDragFrom(null);setDragOver(null);if(source&&key)startSwap(source,key)},onCancel:()=>{dragSource.current=null;setDragFrom(null);setDragOver(null)}});
 const swapPreview=swap?swapDraft(state,month,swap.from,swap.to,swapOverride):null;
 const swapReason=(reason:string)=>({published:t('Reopen the draft first.','יש לפתוח טיוטה תחילה.'),'same-duty':t('Choose another duty.','יש לבחור תורנות אחרת.'),'other-month':t('Swap within the starting month.','ניתן להחליף בתוך חודש ההתחלה.'),unassigned:t('Both duties need an engineer.','יש לשבץ מהנדס בשתי התורנויות.'),locked:t('Unlock these duties before swapping.','יש לבטל נעילה לפני החלפה.'),'same-person':t('These duties already have the same engineer.','שתי התורנויות משובצות לאותו מהנדס.'),duplicate:t('A primary engineer cannot also be the emergency cover.','אותו מהנדס לא יכול למלא את שני התפקידים.'),inactive:t('Choose active engineers.','יש לבחור מהנדסים פעילים.'),availability:t('This swap conflicts with availability.','ההחלפה מתנגשת עם אילוצים.')}[reason]??reason);
 function confirmSwap(){if(!swap)return;const result=swapDraft(state,month,swap.from,swap.to,swapOverride);if(!result.ok){toast.error(swapReason(result.reason));return}update(s=>({...s,assignments:result.assignments}));setSwap(null);toast.success(t('Duties swapped.','התורנויות הוחלפו.'))}
 function exportBackup(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download='duty-demo-backup.json';a.click();URL.revokeObjectURL(url)}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
 try{context.registerTool({name:'read_duty_month',description:'Read the selected demo month, duty blocks, points, and assignments without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');return{month,status:md.status,duties:bs.map(b=>({...b,assignment:state.assignments[b.id]??null}))}}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[state,month,bs,md.status]);
 return <div className="app-shell" dir={lang==='he'?'rtl':'ltr'}><Toaster position="bottom-center" richColors/>
  <header className="topbar"><a className="brand" href="/" aria-label="Duty home"><span className="brand-symbol">d<span>·</span></span> duty<span className="brand-divider"/><span className="brand-context">{t('Engineering','הנדסה')}</span></a><div className="top-actions"><span className="demo-badge">{t('DEMO WORKSPACE','סביבת הדגמה')}</span><Button variant="ghost" size="icon" onClick={()=>setLang(lang==='en'?'he':'en')} aria-label={t('Switch to Hebrew','Switch to English')}><Globe/></Button><button className="avatar admin-avatar" onClick={()=>setHelp(true)} aria-label={t('About this demo','על ההדגמה')}>AM</button></div></header>
  <main className="main-wrap"><div className="workspace-status"><span>{t('Demo · Saved on this device','הדגמה · נשמר במכשיר זה')}</span><Button variant="ghost" size="sm" onClick={()=>setHelp(true)}><Info/>{t('Help','עזרה')}</Button></div>
  <Tabs value={tab} onValueChange={setTab} className="main-tabs"><div className="nav-row"><TabsList variant="line"><TabsTrigger value="schedule"><CalendarDays/>{t('Schedule','לוח תורנויות')}</TabsTrigger><TabsTrigger value="availability"><SlidersHorizontal/>{t('Availability','אילוצים')}</TabsTrigger><TabsTrigger value="team"><Users/>{t('Team & fairness','צוות והוגנות')}</TabsTrigger></TabsList><span className="time-zone">09:00 → 09:00 · {t('Israel time','שעון ישראל')}</span></div>
  <div className="month-toolbar"><div className="month-title"><Button variant="outline" size="icon" onClick={()=>changeMonth(-1)} aria-label={t('Previous month','חודש קודם')}><ChevronLeft/></Button><h2>{monthLabel}</h2><Button variant="outline" size="icon" onClick={()=>changeMonth(1)} aria-label={t('Next month','חודש הבא')}><ChevronRight/></Button><span className={'status-badge '+md.status}>{md.status==='published'?t('Published','פורסם'):t('Draft','טיוטה')}</span></div><div className="toolbar-actions"><Button variant="outline" onClick={()=>setSettings(true)}><SlidersHorizontal/>{t('Month settings','הגדרות חודש')}</Button>{md.status==='published'?<Button onClick={()=>update(s=>s)}>{t('Reopen draft','פתיחת טיוטה')}</Button>:<><Button variant="outline" disabled={busy||!ready||!active.length} onClick={runGenerate}><Sparkles className={busy?'spin':''}/>{busy?t('Generating…','משבץ…'):md.generated?t('Regenerate','שיבוץ מחדש'):t('Generate month','יצירת שיבוץ')}</Button><Button disabled={assigned!==bs.length||!!conflicts.length||!bs.length} onClick={()=>setPublishOpen(true)}><Check/>{t('Publish','פרסום')}</Button></>}</div></div>
  <TabsContent value="schedule" forceMount style={{display:tab==='schedule'?undefined:'none'}}><div className="workspace-grid"><section className="calendar-panel"><div className="calendar-top"><div className="segmented"><button className={view==='team'?'selected':''} onClick={()=>setView('team')}>{t('Whole team','כל הצוות')}</button><button className={view==='me'?'selected':''} onClick={()=>setView('me')}>{t('My duties','התורנויות שלי')}</button></div><Button variant="ghost" onClick={()=>{setSpecialOpen(true);setSpecialTitle('')}}><Plus/>{t('Special block','מקטע מיוחד')}</Button></div>
   <div className="calendar-weekdays">{(lang==='en'?['Sun','Mon','Tue','Wed','Thu','Fri','Sat']:['א׳','ב׳','ג׳','ד׳','ה׳','ו׳','ש׳']).map((d,i)=><span className={i>4?'weekend-label':''} key={d}>{d}</span>)}</div>
   <div ref={drag.container} className="calendar-grid gesture-grid">{dateCells.map(d=>{const b=bs.find(b=>b.start<=d&&d<b.end),a=b?state.assignments[b.id]:undefined,p=state.team.find(p=>p.id===a?.primary),inside=d.startsWith(month),mine=a?.primary==='e0'||a?.secondary==='e0',continued=b&&b.start!==d;return <button disabled={!b} key={d} data-gesture-key={b?.id} onClick={()=>{if(!drag.ignoreClick()&&b){setSwapTarget('none');openDuty(b)}}} className={['day-cell',!inside?'outside':'',b?.kind==='weekend'?'weekend':'',b?.kind==='special'?'special':'',view==='me'&&!mine?'faded':'',dragFrom===b?.id?'drag-source':'',dragOver===b?.id&&dragFrom!==b?.id?'drag-target':'',md.status==='draft'&&a?.primary&&!a.locked?'can-swap':''].join(' ')} aria-label={`${fmt(d)} ${p?.name??t('Unassigned','ללא שיבוץ')}`}><div className="date-line"><span className="mobile-weekday">{fmt(d,{weekday:'short'})}</span><span className="day-number">{Number(d.slice(-2))}</span>{b?.kind==='special'?<span className="tiny-badge">+{b.points-1}</span>:b?.kind==='weekend'?<span className="weekend-word">{t('WEEKEND','סופ״ש')}</span>:null}{a?.locked&&<Lock size={12}/>}</div>{b&&<><div className={'assignment-chip '+(!p?'empty-assignment':'')} style={p?{borderInlineStartColor:p.color,background:p.color,color:'#fff'}:undefined}>{p?<><span className="chip-initial" style={{color:p.color,background:p.color+'16'}}>{p.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><span>{nickname(p.id)}{p.id==='e0'&&<small> {t('(you)','(אני)')}</small>}</span></>:<span>{t('Unassigned','ללא שיבוץ')}</span>}</div><div className="day-meta">{b.kind==='special'?b.title:continued?t('Same duty','אותה תורנות'):b.kind==='weekend'?t('Fri → Sun','ו׳ ← א׳'):'09:00 → 09:00'}</div>{a?.secondary&&<div className="secondary-name">+ {nickname(a.secondary)}</div>}</>}</button>})}</div>
   <div className="calendar-footer"><span><span className="legend-box"/>{t('Fri–Sat = 1 duty point','שישי–שבת = נקודת תורנות אחת')}</span><span><span className="legend-box special-legend"/>{t('Special block','מקטע מיוחד')}</span><span>{t('Tap to edit · Hold & drag to swap','לחצו לעריכה · לחיצה ארוכה וגרירה להחלפה')}</span></div>
   {assigned<bs.length&&<div className="inline-note"><Info size={17}/>{md.generated?t('Uncovered dates need a decision. Open a date to see candidates and override a constraint if necessary.','תאריכים ללא כיסוי דורשים החלטה. פתחו יום לצפייה במועמדים וחריגה מאילוץ במידת הצורך.'):t('Ready when you are. Generate a draft using the team’s availability.','כשתהיו מוכנים, צרו טיוטה לפי אילוצי הצוות.')}</div>}
   {!!conflicts.length&&<div className="warning-note">{t(`${conflicts.length} assignments conflict with availability. Review them before publishing.`,'קיימות התנגשויות עם אילוצים. יש לבדוק אותן לפני פרסום.')}</div>}
   {!!gaps.length&&<div className="inline-note">{t('Spacing to review:','מרווחים לבדיקה:')} {gaps.slice(0,3).map(({p,b})=>`${p.name} · ${fmt(b.start)}`).join(' / ')} — {t('consecutive duties are allowed when needed.','תורנויות רצופות מותרות בעת הצורך.')}</div>}
  </section><aside className="side-panel"><div className="coverage-card"><div className="eyebrow">{t('THIS MONTH','החודש')}</div><div className="coverage-number">{assigned}<span>/ {bs.length}</span></div><div>{t('duties covered','תורנויות משובצות')}</div><div className="coverage-track"><span style={{width:`${assigned/bs.length*100}%`}}/></div><div className="coverage-bottom"><span>{active.length} {t('engineers','מהנדסים')}</span><span>{owned.reduce((v,b)=>v+b.points,0)} {t('base + special pts','נקודות בסיס ומיוחדות')}</span></div></div>
  <div className="fairness-card"><div className="panel-title"><h3>{t('The balance','האיזון')}</h3><span>{t('POINTS','נקודות')}</span></div><div className="balance-list">{active.map((p,i)=><div className="balance-row" key={p.id}><span className="avatar small" style={{background:p.color+'17',color:p.color}}>{p.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><div className="balance-person"><span>{p.name}{p.id==='e0'&&<small> · {t('you','אני')}</small>}</span><div className="balance-track"><span style={{background:p.color,width:`${Math.max(0,monthTotals[p.id])/Math.max(4,...Object.values(monthTotals))*100}%`}}/></div></div><strong>{monthTotals[p.id]||0}</strong></div>)}</div><Button variant="ghost" className="full-width" onClick={()=>setTab('team')}>{t('Manage team & order','ניהול הצוות והסדר')}<ArrowRight/></Button></div>
  <div className="deadline-card"><CalendarDays size={18}/><div><strong>{t('Constraints due','מועד אחרון לאילוצים')}</strong><p>{fmt(md.deadline)} · {t('chosen by you','לבחירתך')}</p></div><button onClick={()=>setSettings(true)}>{t('Edit','עריכה')}</button></div></aside></div></TabsContent>
  <TabsContent value="availability"><section className="availability-panel"><div className="section-heading"><h3>{t('Constraints','אילוצים')}</h3><Picker value={person} onChange={setPerson} label={t('Engineer','מהנדס')} options={active.map(p=>({value:p.id,label:p.name+(p.id==='e0'?t(' (you)',' (אני)'):'' )}))}/></div><AvailabilityEditor state={state} month={month} person={person} cells={dateCells} lang={lang} disabled={md.status==='published'} onSave={saveConstraints}/>{md.status==='published'&&<div className="inline-note">{t('Reopen the draft to edit constraints.','יש לפתוח טיוטה לעריכת אילוצים.')}</div>}</section></TabsContent>
  <TabsContent value="team"><section className="team-panel"><div className="section-heading"><div><h3>{t('Team order','סדר הצוות')}</h3><p>{t('Most senior → newest','הוותיק ביותר ← החדש ביותר')}</p></div><span className="pill">{active.length} {t('active engineers','מהנדסים פעילים')}</span></div><div className="team-list">{state.team.map((p,i)=><div className={'team-row '+(!p.active?'inactive':'')} key={p.id}><span className="rank">{String(i+1).padStart(2,'0')}</span><span className="avatar" style={{background:p.color+'18',color:p.color}}>{p.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><div className="team-name"><strong>{p.name}</strong><small>{p.id==='e0'?t('Manager + engineer','מנהל ומהנדס'):i===state.team.length-1?t('Newest teammate','חבר הצוות החדש ביותר'):t('Engineer','מהנדס')}</small></div><div className="team-points"><strong>{monthTotals[p.id]??0}</strong><span>{t('this month','החודש')}</span></div><div className="team-points total-points"><strong>{historyTotals[p.id]??0}</strong><span>{t('all months','כל החודשים')}</span></div><div className="order-buttons"><Button variant="ghost" size="icon" disabled={i===0} aria-label={`${t('Move up','הזזה למעלה')} ${p.name}`} onClick={()=>update(s=>{const team=[...s.team];[team[i-1],team[i]]=[team[i],team[i-1]];return{...s,team}},false)}><ArrowUp/></Button><Button variant="ghost" size="icon" disabled={i===state.team.length-1} aria-label={`${t('Move down','הזזה למטה')} ${p.name}`} onClick={()=>update(s=>{const team=[...s.team];[team[i+1],team[i]]=[team[i],team[i+1]];return{...s,team}},false)}><ArrowDown/></Button></div><label className="active-checkbox"><Checkbox checked={p.active} onCheckedChange={v=>{update(s=>({...s,team:s.team.map(x=>x.id===p.id?{...x,active:!!v}:x)}),false);toast(t('Existing assignments are retained for review.','שיבוצים קיימים נשמרים לבדיקה.'))}}/>{t('Active','פעיל')}</label></div>)}</div><form className="add-member" onSubmit={e=>{e.preventDefault();if(!newName.trim())return;update(s=>({...s,team:[...s.team,{id:crypto.randomUUID(),name:newName.trim(),color:'#526f80',active:true}]}),false);setNewName('')}}><input aria-label={t('New engineer name','שם מהנדס חדש')} maxLength={50} placeholder={t('New teammate’s name','שם חבר צוות חדש')} value={newName} onChange={e=>setNewName(e.target.value)}/><Button type="submit" disabled={!newName.trim()}><Plus/>{t('Add engineer','הוספת מהנדס')}</Button></form></section></TabsContent>
  </Tabs><footer className="app-footer"><span>Duty</span><button onClick={exportBackup}><Download size={14}/>{t('Export demo backup','ייצוא גיבוי ההדגמה')}</button></footer></main>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="duty-dialog" dir={lang==='he'?'rtl':'ltr'}><DialogHeader><DialogTitle>{selected?.title||t('Edit duty','עריכת תורנות')}</DialogTitle><DialogDescription>{selected&&`${fmt(selected.start)} 09:00 → ${fmt(selected.end)} 09:00 · ${selected.points} ${t('fairness points','נקודות הוגנות')}`}</DialogDescription></DialogHeader>{carry?<div className="inline-note">{t('This duty belongs to the month in which it starts. Edit it there to keep both months consistent.','התורנות שייכת לחודש שבו היא מתחילה. יש לערוך אותה שם כדי לשמור על עקביות.')}<Button onClick={()=>{setMonth(selected!.start.slice(0,7));setSelected(null)}}>{t('Open starting month','פתיחת חודש ההתחלה')}</Button></div>:<><label className="field-label">{t('Primary engineer','מהנדס ראשי')}<Picker value={primary} onChange={v=>{setPrimary(v);setOverride(false)}} label={t('Primary engineer','מהנדס ראשי')} options={[{value:'none',label:t('Leave unassigned','ללא שיבוץ')},...state.team.filter(p=>p.active||p.id===primary).map(p=>({value:p.id,label:p.name+(selected&&unavailable(selected,p.id,state.constraints).length?t(' · unavailable',' · לא זמין'):'')}))]}/></label><label className="field-label">{t('Emergency second engineer','מהנדס נוסף למקרה חירום')}<Picker value={secondary} onChange={v=>{setSecondary(v);setOverride(false)}} label={t('Second engineer','מהנדס נוסף')} options={[{value:'none',label:t('Not needed','לא נדרש')},...state.team.filter(p=>p.active||p.id===secondary).map(p=>({value:p.id,label:p.name+(selected&&unavailable(selected,p.id,state.constraints).length?t(' · unavailable',' · לא זמין'):'' )}))]}/></label><label className="check-label"><Checkbox checked={locked} onCheckedChange={v=>setLocked(!!v)}/><span>{t('Keep this assignment when regenerating','שמירת השיבוץ בעת יצירה מחדש')}</span></label>{!!editConflicts.length&&<div className="warning-note"><strong>{t('Availability conflict','התנגשות עם אילוץ')}</strong><p>{editConflicts.join(' / ')}</p><label className="check-label"><Checkbox checked={override} onCheckedChange={v=>setOverride(!!v)}/>{t('Override these constraints as manager','חריגה מאילוצים אלה בהחלטת מנהל')}</label></div>}{md.status==='draft'&&selected&&<div className="swap-picker"><label className="field-label">{t('Swap primary with','החלפת מהנדס ראשי עם')}<Picker value={swapTarget} onChange={setSwapTarget} label={t('Duty to swap','תורנות להחלפה')} options={[{value:'none',label:t('Choose a duty','בחירת תורנות')},...bs.filter(b=>b.id!==selected.id&&b.start.slice(0,7)===month&&state.assignments[b.id]?.primary).map(b=>({value:b.id,label:`${fmt(b.start)} · ${nickname(state.assignments[b.id]?.primary)}`}))]}/></label><Button variant="outline" disabled={swapTarget==='none'} onClick={()=>{startSwap(selected.id,swapTarget);setSelected(null)}}>{t('Review swap','בדיקת החלפה')}</Button></div>}
<p className="muted-copy">{t('The second engineer receives the same points. Changes return the month to draft.','המהנדס הנוסף מקבל אותן נקודות. שינויים מחזירים את החודש לטיוטה.')}</p><Button disabled={!!editConflicts.length&&!override} onClick={saveDuty}>{t('Save assignment','שמירת השיבוץ')}</Button>{selected?.kind==='special'&&<Button variant="ghost" onClick={()=>{const b=selected;update(s=>{const assignments={...s.assignments};delete assignments[b.id];return{...s,assignments,specials:s.specials.filter(x=>x.start!==b.start)}});setSelected(null)}}><Trash2/>{t('Remove special block & assignment','הסרת המקטע המיוחד והשיבוץ')}</Button>}</>}</DialogContent></Dialog>
 <Dialog open={!!swap} onOpenChange={v=>!v&&setSwap(null)}><DialogContent dir={lang==='he'?'rtl':'ltr'}><DialogHeader><DialogTitle>{t('Swap duties','החלפת תורנויות')}</DialogTitle><DialogDescription>{t('Primary engineers swap. Emergency cover stays on its dates.','המהנדסים הראשיים מתחלפים. כיסוי החירום נשאר בתאריכים שלו.')}</DialogDescription></DialogHeader>{swap&&<><div className="swap-review">{[swap.from,swap.to].map((id,i)=>{const b=bs.find(b=>b.id===id),other=i===0?swap.to:swap.from;return <div key={id}><strong>{fmt(id)}{b&&b.end!==addDays(id,1)?` – ${fmt(addDays(b.end,-1))}`:''}</strong><span>{nickname(state.assignments[id]?.primary)} → <b>{nickname(state.assignments[other]?.primary)}</b></span><small>{b?.points} {t('points','נקודות')}</small></div>})}</div>{swapPreview&&!swapPreview.ok&&<div className="warning-note">{swapReason(swapPreview.reason)}</div>}{!!swapPreview?.conflicts?.length&&<div className="warning-note"><p>{swapPreview.conflicts.map(c=>`${personName(c.person)} · ${fmt(c.date)}${state.constraintNotes?.[c.person]?.[c.date]?' · '+state.constraintNotes[c.person][c.date]:''}`).join(' / ')}</p><label className="check-label"><Checkbox checked={swapOverride} onCheckedChange={v=>setSwapOverride(!!v)}/>{t('Override these constraints as manager','חריגה מאילוצים בהחלטת מנהל')}</label></div>}<Button disabled={!swapPreview?.ok} onClick={confirmSwap}>{t('Confirm swap','אישור החלפה')}</Button></>}</DialogContent></Dialog>
 <Dialog open={specialOpen} onOpenChange={setSpecialOpen}><DialogContent dir={lang==='he'?'rtl':'ltr'}><DialogHeader><DialogTitle>{t('A special duty block','מקטע תורנות מיוחד')}</DialogTitle><DialogDescription>{t('One engineer covers the whole block. You decide how much it counts.','מהנדס אחד מכסה את כל המקטע. אתם קובעים כמה הוא שווה.')}</DialogDescription></DialogHeader><label className="field-label">{t('Name','שם')}<input maxLength={60} value={specialTitle} onChange={e=>setSpecialTitle(e.target.value)} placeholder={t('e.g. Holiday coverage','למשל: כיסוי חג')}/></label><div className="form-pair"><label className="field-label">{t('First duty date','יום תורנות ראשון')}<input type="date" value={specialStart} min={month+'-01'} max={addDays(monthNext(month)+'-01',-1)} onChange={e=>{setSpecialStart(e.target.value);if(specialEnd<e.target.value)setSpecialEnd(e.target.value)}}/></label><label className="field-label">{t('Last duty date','יום תורנות אחרון')}<input type="date" min={specialStart} value={specialEnd} onChange={e=>setSpecialEnd(e.target.value)}/></label></div><label className="field-label">{t('Extra fairness points','נקודות הוגנות נוספות')}<input type="number" min="0" max="20" step="0.5" value={extra} onChange={e=>setExtra(e.target.value)}/></label><div className="special-summary"><strong>{1+Number(extra)||1} {t('total points','נקודות בסך הכול')}</strong><span>{t('1 base point + your extra points','נקודת בסיס אחת + הנקודות הנוספות שבחרת')}</span><span>{specialStart&&specialEnd&&`${fmt(specialStart)} 09:00 → ${fmt(addDays(specialEnd,1))} 09:00`}</span></div><p className="muted-copy">{t('Replaces duties in these dates, including weekends. Affected assignments are cleared for review.','מחליף את התורנויות בתאריכים אלה, כולל סופי שבוע. השיבוצים המושפעים ינוקו לבדיקה מחדש.')}</p><Button onClick={addSpecial}>{t('Add special block','הוספת מקטע מיוחד')}</Button></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent dir={lang==='he'?'rtl':'ltr'}><DialogHeader><DialogTitle>{t('Month settings','הגדרות חודש')} · {monthLabel}</DialogTitle><DialogDescription>{t('Choose when the team should finish entering next month’s constraints.','בחרו עד מתי הצוות יזין את האילוצים לחודש הבא.')}</DialogDescription></DialogHeader><label className="field-label">{t('Constraints deadline','מועד אחרון לאילוצים')}<input type="date" value={md.deadline} onChange={e=>{if(e.target.value)update(s=>({...s,months:{...s.months,[month]:{...md,deadline:e.target.value}}}),false)}}/></label><p className="muted-copy">{t('The demo records your deadline. Notifications and employee access will be connected in the next milestone.','ההדגמה שומרת את המועד. התראות וגישה לעובדים יחוברו באבן הדרך הבאה.')}</p><Button onClick={()=>setSettings(false)}>{t('Done','סיום')}</Button></DialogContent></Dialog>
 <Dialog open={publishOpen} onOpenChange={setPublishOpen}><DialogContent dir={lang==='he'?'rtl':'ltr'}><DialogHeader><DialogTitle>{t('Ready to publish?','מוכנים לפרסום?')}</DialogTitle><DialogDescription>{monthLabel} · {assigned} {t('duties covered','תורנויות משובצות')}</DialogDescription></DialogHeader><div className="publish-summary"><CheckCircle2 size={30}/><p>{t('All duty blocks have a primary engineer. Your draft will be marked published in this demo.','לכל מקטע שובץ מהנדס ראשי. הטיוטה תסומן כמפורסמת בהדגמה.')}</p></div><p className="muted-copy">{t('No notifications are sent yet. You can reopen and adjust this schedule any time.','עדיין לא נשלחות התראות. ניתן לפתוח ולערוך מחדש בכל עת.')}</p><Button onClick={()=>{update(s=>({...s,months:{...s.months,[month]:{...md,status:'published',generated:true}}}),false);setPublishOpen(false);toast.success(t('Month published in the demo.','החודש פורסם בהדגמה.'))}}>{t('Publish demo schedule','פרסום לוח ההדגמה')}</Button></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent dir={lang==='he'?'rtl':'ltr'}><DialogHeader><DialogTitle>{t('Your first working rota','לוח התורנויות הראשון שלך')}</DialogTitle><DialogDescription>{t('Milestone 1 · A private demo with fictional people','אבן דרך 1 · הדגמה פרטית עם אנשים לדוגמה')}</DialogDescription></DialogHeader><ol className="guide-list"><li>{t('Set availability and reorder the team from most senior to newest.','הזינו אילוצים וסדרו את הצוות מהוותיק ביותר לחדש ביותר.')}</li><li>{t('Add special blocks with dates and extra points, then generate the month.','הוסיפו מקטעים מיוחדים עם תאריכים ונקודות, ואז צרו שיבוץ לחודש.')}</li><li>{t('Tap to edit; hold and drag one duty onto another to swap. Locked duties stay fixed.','לחצו לעריכה; לחיצה ארוכה וגרירה בין תורנויות מחליפה אותן. תורנויות נעולות נשמרות.')}</li><li>{t('Review points and publish. Generate the next month to see fairness carry forward.','בדקו את הנקודות ופרסמו. צרו את החודש הבא כדי לבדוק איזון לאורך זמן.')}</li></ol><div className="inline-note">{t('Google sign-in, a shared database, push notifications, calendar subscriptions and swap requests are the next milestone. This demo stays on this browser and is not a live team schedule.','התחברות עם גוגל, מסד נתונים משותף, התראות, מנויי יומן ובקשות החלפה יתווספו בהמשך. ההדגמה נשמרת בדפדפן זה ואינה לוח חי לצוות.')}</div><Button onClick={()=>setHelp(false)}>{t('Let’s plan','מתחילים לתכנן')}</Button></DialogContent></Dialog>
 </div>
}
