'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import type {TeamWorkspace} from '@/hooks/use-team-workspace';
export function AccessScreen({remote}:{remote:TeamWorkspace}){
 const [lang,setLang]=useState<'en'|'he'>('en'),t=(en:string,he:string)=>lang==='en'?en:he;
 const pending=!!remote.user,rejected=remote.me?.status==='rejected',inactive=remote.me?.status==='approved'&&!remote.me.active;
 return <main className="access-page" dir={lang==='he'?'rtl':'ltr'}><section className="access-card"><div className="access-top"><span className="brand"><span className="brand-symbol">d<span>·</span></span> duty</span><Button variant="ghost" onClick={()=>setLang(lang==='en'?'he':'en')}>{lang==='en'?'עברית':'English'}</Button></div><h1>{remote.loading?t('Opening your workspace…','פותח את סביבת הצוות…'):pending?rejected?t('Request declined','הבקשה נדחתה'):inactive?t('Membership inactive','החברות אינה פעילה'):t('Waiting for approval','ממתין לאישור'):t('Your team’s duty calendar','לוח התורנויות של הצוות')}</h1><p>{pending?t('Your manager must approve your membership before you can enter the team workspace.','המנהל צריך לאשר את חברותך לפני הכניסה לסביבת הצוות.'):t('Sign in with Google to request access.','יש להתחבר עם גוגל כדי לבקש גישה.')}</p>{remote.user?.email&&<small>{remote.user.email}</small>}{remote.error&&<div className="warning-note" role="alert">{remote.error}</div>}{!remote.loading&&(pending?<div className="access-actions"><Button onClick={()=>remote.refresh().catch(()=>{})}>{t('Check approval','בדיקת אישור')}</Button><Button variant="outline" onClick={()=>remote.signOut()}>{t('Sign out','יציאה')}</Button></div>:<Button onClick={()=>remote.signIn()}>{t('Continue with Google','המשך עם גוגל')}</Button>)}<a href="/demo">{t('Explore the demo','סיור בהדגמה')}</a></section></main>
}
