'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,MessageSquare,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {useHoldDrag} from '@/hooks/use-hold-drag';
import {dates,addDays,type State} from '@/lib/rota/engine';
export function AvailabilityEditor({state,month,person,cells,lang,disabled,onSave}:{state:State;month:string;person:string;cells:string[];lang:'en'|'he';disabled:boolean;onSave:(days:string[],kind:'no'|'prefer'|'clear',note:string)=>void}){
 const t=(a:string,b:string)=>lang==='en'?a:b;
 const [selection,setSelection]=useState<string[]>([]),[kind,setKind]=useState<'no'|'prefer'|'clear'>('no'),[note,setNote]=useState(''),[first,setFirst]=useState(month+'-01'),[last,setLast]=useState(month+'-01');
 const anchor=useRef(''),base=useRef<string[]>([]),selectionRef=useRef(selection);selectionRef.current=selection;
 useEffect(()=>{setSelection([]);setNote('');setFirst(month+'-01');setLast(month+'-01')},[person,month]);
 const gesture=useHoldDrag({enabled:!disabled,onStart:key=>{base.current=[...selectionRef.current];anchor.current=key;setSelection([...new Set([...base.current,key])]);},onMove:key=>{const a=anchor.current;if(!a)return;setSelection([...new Set([...base.current,...dates(a<key?a:key,addDays(a<key?key:a,1))])].filter(d=>d.startsWith(month)));},onEnd:()=>{anchor.current=''},onCancel:()=>{setSelection(base.current);anchor.current=''}});
 function toggle(d:string){if(gesture.ignoreClick()||disabled)return;const previous=selectionRef.current;if(!previous.length){setNote(state.constraintNotes?.[person]?.[d]??'');setKind(state.constraints[person]?.[d]??'no')}setSelection(previous.includes(d)?previous.filter(x=>x!==d):[...previous,d]);}
 const title=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString(lang==='en'?'en-GB':'he-IL',{day:'numeric',month:'short'});
 const saved=Object.entries(state.constraints[person]??{}).filter(([d])=>d.startsWith(month)).sort(([a],[b])=>a.localeCompare(b));
 return <div className="constraint-editor"><p className="gesture-hint">{t('Tap dates, or hold and drag. Then save.','בחרו ימים בלחיצה או בלחיצה ארוכה וגרירה, ואז שמרו.')}</p>
  <div ref={gesture.container} className="availability-grid gesture-grid">{cells.map(d=>{const status=state.constraints[person]?.[d],outside=!d.startsWith(month),selected=selection.includes(d),n=state.constraintNotes?.[person]?.[d];return <button key={d} type="button" data-gesture-key={!outside?d:undefined} disabled={disabled||outside} onClick={()=>toggle(d)} aria-pressed={selected} aria-label={`${title(d)} · ${status==='no'?t('Unavailable','לא זמין'):status==='prefer'?t('Preferred','מועדף'):t('Available','זמין')}${n?' · '+n:''}`} className={['availability-day',outside?'outside':'',status??'',selected?'date-selected':''].join(' ')}><span>{new Date(d+'T12:00:00Z').toLocaleDateString(lang==='en'?'en-GB':'he-IL',{weekday:'short'})}</span><strong>{Number(d.slice(-2))}</strong><span>{status==='no'?'×':status==='prefer'?'✓':'·'}</span>{n&&<MessageSquare className="date-note-icon" size={11}/>}</button>})}</div>
  <div className="constraint-form"><div className="selection-heading"><strong>{selection.length} {t('selected','נבחרו')}</strong><Button size="sm" variant="ghost" disabled={!selection.length} onClick={()=>setSelection([])}><RotateCcw/>{t('Clear selection','ניקוי בחירה')}</Button></div>
   <div className="range-row"><label>{t('From','מ־')}<input type="date" value={first} min={cells.find(d=>d.startsWith(month))} max={[...cells].reverse().find(d=>d.startsWith(month))} onChange={e=>setFirst(e.target.value)}/></label><label>{t('To','עד')}<input type="date" value={last} min={first} max={[...cells].reverse().find(d=>d.startsWith(month))} onChange={e=>setLast(e.target.value)}/></label><Button variant="outline" disabled={disabled||!first||!last||last<first||!first.startsWith(month)||!last.startsWith(month)} onClick={()=>setSelection([...new Set([...selection,...dates(first,addDays(last,1))])])}>{t('Select range','בחירת טווח')}</Button></div>
   <label className="field-label">{t('Availability','זמינות')}<Select value={kind} onValueChange={v=>setKind(v as typeof kind)}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="no">{t('Unavailable','לא זמין')}</SelectItem><SelectItem value="prefer">{t('Prefer to work','מעדיף לעבוד')}</SelectItem><SelectItem value="clear">{t('Remove constraint','הסרת אילוץ')}</SelectItem></SelectContent></Select></label>
   {kind!=='clear'&&<label className="field-label">{t('Note (optional)','הערה (לא חובה)')}<textarea value={note} maxLength={300} rows={2} placeholder={t('e.g. Vacation, appointment…','למשל: חופשה, תור…')} onChange={e=>setNote(e.target.value)}/></label>}
   <Button disabled={disabled||!selection.length} onClick={()=>{onSave(selection,kind,note);setSelection([]);setNote('')}}><Check/>{t('Save selected dates','שמירת הימים שנבחרו')}</Button>
  </div>
  {!!saved.length&&<details className="saved-constraints"><summary>{t('Saved constraints','אילוצים שנשמרו')} ({saved.length})</summary><div>{saved.map(([d,status])=><button key={d} disabled={disabled} onClick={()=>{setSelection([d]);setKind(status);setNote(state.constraintNotes?.[person]?.[d]??'')}}><strong>{title(d)}</strong><span className={'constraint-status '+status}>{status==='no'?t('Unavailable','לא זמין'):t('Preferred','מועדף')}</span>{state.constraintNotes?.[person]?.[d]&&<span>{state.constraintNotes[person][d]}</span>}</button>)}</div></details>}
 </div>
}
