'use client';
import {useRef,useState} from 'react';
import {GripVertical} from 'lucide-react';
import type {Role} from '@/lib/supabase/snapshot';
import {Checkbox} from '@/components/ui/checkbox';
import {useHoldDrag} from '@/hooks/use-hold-drag';
import {ink,type Engineer} from '@/lib/rota/engine';
export function TeamList({team,monthTotals,historyTotals,lang,onReorder,onActive,readOnly=false,selfId='e0',roles=[],onRole}:{roles?:Role[];onRole?:(id:string,role:string)=>void;readOnly?:boolean;selfId?:string;team:Engineer[];monthTotals:Record<string,number>;historyTotals:Record<string,number>;lang:'en'|'he';onReorder:(team:Engineer[])=>void;onActive:(id:string,active:boolean)=>void}){
 const t=(a:string,b:string)=>lang==='en'?a:b,source=useRef<string|null>(null);
 const [dragging,setDragging]=useState<string|null>(null),[over,setOver]=useState<string|null>(null),[announcement,setAnnouncement]=useState('');
 function move(from:string,to:string){const a=team.findIndex(p=>p.id===from),b=team.findIndex(p=>p.id===to);if(a<0||b<0||a===b)return;const next=[...team];next.splice(b,0,next.splice(a,1)[0]);onReorder(next);setAnnouncement(`${team[a].name} · ${b+1}`)}
 function clear(){source.current=null;setDragging(null);setOver(null)}
 const gesture=useHoldDrag({enabled:!readOnly,onStart:id=>{source.current=id;setDragging(id)},onMove:setOver,onEnd:id=>{if(id&&source.current)move(source.current,id);clear()},onCancel:clear});
 return <><p style={{display:readOnly?'none':undefined}} className="gesture-hint">{t('Hold & drag to reorder · Senior → newest','לחיצה ארוכה וגרירה לשינוי הסדר · ותיק ← חדש')}</p><span className="sr-only" aria-live="polite">{announcement}</span><div ref={gesture.container} className="team-list gesture-grid">{team.map((p,i)=><div data-gesture-key={p.id} key={p.id} className={['team-row',!p.active?'inactive':'',dragging===p.id?'drag-source':'',over===p.id&&dragging!==p.id?'drag-target':''].join(' ')}><button disabled={readOnly} className="team-grip" aria-label={`${t('Drag to reorder','גרירה לשינוי הסדר')} ${p.name}`} aria-describedby="team-keyboard-hint" onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();const target=team[i+(e.key==='ArrowUp'?-1:1)];if(target)move(p.id,target.id)}}}><GripVertical size={18}/><span>{i+1}</span></button><span className="avatar" style={{background:p.color,color:ink(p.color)}}>{p.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><div className="team-name"><strong>{p.name}</strong><small>{roles.find(r=>r.code===p.role)?.can_manage?t('Admin + engineer','מנהל ומהנדס'):p.id===selfId?t('You','אני'):i===team.length-1?t('Newest teammate','חבר הצוות החדש ביותר'):t('Engineer','מהנדס')}</small></div><div className="team-points"><strong>{monthTotals[p.id]??0}</strong><span>{t('this month','החודש')}</span></div><div className="team-points total-points"><strong>{historyTotals[p.id]??0}</strong><span>{t('all months','כל החודשים')}</span></div><label className="team-role" style={{display:readOnly?'none':undefined}} onPointerDown={e=>e.stopPropagation()} onTouchStart={e=>e.stopPropagation()}><span className="sr-only">{t('Role','תפקיד')} {p.name}</span><select aria-label={`${t('Role','תפקיד')} ${p.name}`} value={p.role??'engineer'} onChange={e=>onRole?.(p.id,e.target.value)}>{roles.map(r=><option key={r.code} value={r.code}>{lang==='he'?(r.can_manage?'מנהל':'מהנדס'):r.label}</option>)}</select></label><label style={{display:readOnly?'none':undefined}} className="active-checkbox" onPointerDown={e=>e.stopPropagation()} onTouchStart={e=>e.stopPropagation()}><Checkbox disabled={p.id===selfId} checked={p.active} onCheckedChange={v=>onActive(p.id,!!v)}/>{t('Active','פעיל')}</label></div>)}</div><span id="team-keyboard-hint" className="sr-only">{t('Use up and down keys to reorder.','אפשר להשתמש במקשי למעלה ולמטה לשינוי הסדר.')}</span></>
}
